-- 设备工时保养判定：H2（MODE=MySQL）自动建表脚本。
-- 所有时刻字段均为 UTC（TIMESTAMP WITH TIME ZONE），分钟数为非负整数。
-- 多保养项目：每台设备登记时自动生成 item_code='DEFAULT' 的项目（周期取登记周期），
-- 旧接口全部作用于 DEFAULT；新增项目经 /items 接口创建，创建后不可修改或删除。

-- 设备主表：每台设备一行，版本号用于写操作乐观并发控制。
CREATE TABLE IF NOT EXISTS equipment (
    equipment_id VARCHAR(64) NOT NULL PRIMARY KEY,
    maintenance_period_minutes BIGINT NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
COMMENT ON TABLE equipment IS '设备主表：每台设备一行';
COMMENT ON COLUMN equipment.equipment_id IS '设备唯一标识（客户端提供）';
COMMENT ON COLUMN equipment.maintenance_period_minutes IS '登记时的原保养周期（分钟），正整数，登记后不可修改；已迁移为 DEFAULT 项目周期';
COMMENT ON COLUMN equipment.version IS '设备版本号，初始 1；项目新增/读数新增修订/任一项目保养均校验 expectedVersion 并加一';
COMMENT ON COLUMN equipment.created_at IS '登记时刻（UTC）';

-- 保养项目表：设备内 item_code 唯一；DEFAULT 随设备登记创建，其余项目创建后不可修改或删除。
CREATE TABLE IF NOT EXISTS maintenance_item (
    equipment_id VARCHAR(64) NOT NULL,
    item_code VARCHAR(64) NOT NULL,
    maintenance_period_minutes BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (equipment_id, item_code)
);
COMMENT ON TABLE maintenance_item IS '保养项目：每台设备一个 DEFAULT 项目（迁移自登记周期），新增接口最多再加 20 个，创建后不可修改或删除';
COMMENT ON COLUMN maintenance_item.equipment_id IS '所属设备标识';
COMMENT ON COLUMN maintenance_item.item_code IS '项目编码，设备内唯一；DEFAULT 为登记时迁移的默认项目，不可通过新增接口重复创建';
COMMENT ON COLUMN maintenance_item.maintenance_period_minutes IS '该项目独立保养周期（分钟），正整数，创建后不可修改';
COMMENT ON COLUMN maintenance_item.created_at IS '项目创建时刻（UTC）；DEFAULT 项目为设备登记时刻';

-- 工时读数当前值表：reading_id 设备内唯一，同设备同一采样时刻仅一条。
-- 读数由设备的全部保养项目共享；被任一项目保养记录引用的读数不可修订。
CREATE TABLE IF NOT EXISTS reading (
    equipment_id VARCHAR(64) NOT NULL,
    reading_id VARCHAR(64) NOT NULL,
    sampled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cumulative_minutes BIGINT NOT NULL,
    revision_no INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (equipment_id, reading_id),
    CONSTRAINT uq_reading_sampled_at UNIQUE (equipment_id, sampled_at)
);
COMMENT ON TABLE reading IS '工时读数当前值：所有保养项目共享；按采样时刻排序后累计分钟须单调不减';
COMMENT ON COLUMN reading.equipment_id IS '所属设备标识';
COMMENT ON COLUMN reading.reading_id IS '读数标识，设备内唯一';
COMMENT ON COLUMN reading.sampled_at IS 'UTC 采样时刻；同设备同一时刻仅允许一条读数';
COMMENT ON COLUMN reading.cumulative_minutes IS '当前累计工时（分钟），非负整数，随修订更新';
COMMENT ON COLUMN reading.revision_no IS '当前修订号，初始 1，每次修订加一';
COMMENT ON COLUMN reading.created_at IS '读数登记时刻（UTC）';
COMMENT ON COLUMN reading.updated_at IS '最近一次修订时刻（UTC）';

-- 读数修订历史：每次修订追加一行，保留全部历史值。
CREATE TABLE IF NOT EXISTS reading_revision (
    equipment_id VARCHAR(64) NOT NULL,
    reading_id VARCHAR(64) NOT NULL,
    revision_no INT NOT NULL,
    cumulative_minutes BIGINT NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (equipment_id, reading_id, revision_no)
);
COMMENT ON TABLE reading_revision IS '读数修订历史：revision_no=1 为初始登记值，其后每行对应一次修订';
COMMENT ON COLUMN reading_revision.equipment_id IS '所属设备标识';
COMMENT ON COLUMN reading_revision.reading_id IS '读数标识';
COMMENT ON COLUMN reading_revision.revision_no IS '修订号，从 1 开始递增';
COMMENT ON COLUMN reading_revision.cumulative_minutes IS '该修订版本的累计工时（分钟）';
COMMENT ON COLUMN reading_revision.request_id IS '产生该修订的请求 requestId';
COMMENT ON COLUMN reading_revision.created_at IS '该修订生效时刻（UTC）';

-- 保养记录：每个项目独立成行，锚定某读数的特定修订号，保存锚点时刻与工时快照，不允许删除。
-- 同一读数可被不同项目分别锚定；同一项目内锚点时间须严格递增。
CREATE TABLE IF NOT EXISTS maintenance (
    maintenance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id VARCHAR(64) NOT NULL,
    item_code VARCHAR(64) NOT NULL,
    reading_id VARCHAR(64) NOT NULL,
    anchor_revision_no INT NOT NULL,
    anchor_sampled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    anchor_cumulative_minutes BIGINT NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_maintenance_item FOREIGN KEY (equipment_id, item_code)
        REFERENCES maintenance_item (equipment_id, item_code)
);
CREATE INDEX IF NOT EXISTS idx_maintenance_equipment_item
    ON maintenance (equipment_id, item_code, anchor_sampled_at);
CREATE INDEX IF NOT EXISTS idx_maintenance_reading
    ON maintenance (equipment_id, reading_id);
COMMENT ON TABLE maintenance IS '保养记录：按项目独立维护；项目内锚点时间须严格晚于上次锚点；被任一项目记录引用的读数不可再修订';
COMMENT ON COLUMN maintenance.maintenance_id IS '保养记录自增主键';
COMMENT ON COLUMN maintenance.equipment_id IS '所属设备标识';
COMMENT ON COLUMN maintenance.item_code IS '保养项目编码（DEFAULT 为旧接口操作的默认项目）';
COMMENT ON COLUMN maintenance.reading_id IS '锚点读数标识；同一读数可作为不同项目的锚点';
COMMENT ON COLUMN maintenance.anchor_revision_no IS '锚点读数在保养完成时的修订号';
COMMENT ON COLUMN maintenance.anchor_sampled_at IS '锚点读数的 UTC 采样时刻（快照）';
COMMENT ON COLUMN maintenance.anchor_cumulative_minutes IS '锚点读数在保养完成时的累计工时快照（分钟）';
COMMENT ON COLUMN maintenance.request_id IS '完成保养请求的 requestId';
COMMENT ON COLUMN maintenance.completed_at IS '保养完成登记时刻（UTC）';

-- 幂等去重表：requestId 全局唯一；仅成功结果占键，失败回滚不占键。
CREATE TABLE IF NOT EXISTS idempotency_request (
    request_id VARCHAR(128) NOT NULL PRIMARY KEY,
    operation VARCHAR(48) NOT NULL,
    request_fingerprint VARCHAR(512) NOT NULL,
    response_body CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
COMMENT ON TABLE idempotency_request IS '写操作幂等去重：同键同参重放原成功结果，同键异参返回 409';
COMMENT ON COLUMN idempotency_request.request_id IS '全局唯一请求标识';
COMMENT ON COLUMN idempotency_request.operation IS '操作类型（登记设备/新增项目/新增读数/修订/完成保养）';
COMMENT ON COLUMN idempotency_request.request_fingerprint IS '业务参数指纹（不含 requestId），用于同键异参判定';
COMMENT ON COLUMN idempotency_request.response_body IS '原成功响应报文（JSON），重放时原样返回';
COMMENT ON COLUMN idempotency_request.created_at IS '首次成功处理时刻（UTC）';
