-- 设备工时保养判定：H2（MODE=MySQL）自动建表脚本。
-- 所有时刻字段均为 UTC（TIMESTAMP WITH TIME ZONE）；工时表链条以“小时”为单位（DECIMAL，6 位小数），
-- cumulative_minutes 为虚拟工时小时换算的分钟缓存值（四舍五入）， legacy 读数与之一致。

-- 设备主表：每台设备一行，版本号用于写操作乐观并发控制。
CREATE TABLE IF NOT EXISTS equipment (
    equipment_id VARCHAR(64) NOT NULL PRIMARY KEY,
    maintenance_period_minutes BIGINT NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
COMMENT ON TABLE equipment IS '设备主表：每台设备一行';
COMMENT ON COLUMN equipment.equipment_id IS '设备唯一标识（客户端提供），同时作为初始 ACTIVE 工时表的 meterKey';
COMMENT ON COLUMN equipment.maintenance_period_minutes IS '保养周期（分钟），正整数，登记后不可修改';
COMMENT ON COLUMN equipment.version IS '设备版本号，初始 1；新增读数/修订/完成保养/更换工时表均校验 expectedVersion 并加一';
COMMENT ON COLUMN equipment.created_at IS '登记时刻（UTC）';

-- 工时表（meter）更换链：同设备按 seq_no 线性链接，任意时刻仅一张 ACTIVE；不可成环。
-- virtualHours(meter, raw) = offset_hours + raw - initial_raw_hours，offset 在更换时按前驱表最后有效读数冻结。
CREATE TABLE IF NOT EXISTS meter (
    equipment_id VARCHAR(64) NOT NULL,
    meter_key VARCHAR(64) NOT NULL,
    status VARCHAR(8) NOT NULL,
    seq_no INT NOT NULL,
    predecessor_key VARCHAR(64),
    replacement_key VARCHAR(128),
    initial_raw_hours DECIMAL(22,6) NOT NULL,
    final_raw_hours DECIMAL(22,6),
    offset_hours DECIMAL(22,6) NOT NULL,
    recalc_version INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (equipment_id, meter_key),
    CONSTRAINT uq_meter_key_global UNIQUE (meter_key),
    CONSTRAINT chk_meter_status CHECK (status IN ('ACTIVE', 'CLOSED'))
);
COMMENT ON TABLE meter IS '工时表更换链：按 seq_no 线性后继；同设备仅一张 ACTIVE；virtualHours=offset_hours+raw-initial_raw_hours';
COMMENT ON COLUMN meter.equipment_id IS '所属设备标识';
COMMENT ON COLUMN meter.meter_key IS '工时表唯一标识，全局唯一；初始表 meterKey 与 equipmentId 相同';
COMMENT ON COLUMN meter.status IS '状态：ACTIVE（当前表，可登记读数）/ CLOSED（已被更换，只读，读数仍可按规则修订）';
COMMENT ON COLUMN meter.seq_no IS '链内序号，初始表为 0，每次更换加一';
COMMENT ON COLUMN meter.predecessor_key IS '前驱表 meterKey；初始表为 NULL';
COMMENT ON COLUMN meter.replacement_key IS '使本表产生（新表）/关闭本表（旧表）的更换请求 replacementKey；初始表为 NULL';
COMMENT ON COLUMN meter.initial_raw_hours IS '本表登记时的新表初始原始读数（小时），非负；表内读数不得小于该值';
COMMENT ON COLUMN meter.final_raw_hours IS '关表最终原始读数（小时），非负且不小于关表时最后有效读数；ACTIVE 时为 NULL；之后不可变';
COMMENT ON COLUMN meter.offset_hours IS '虚拟工时偏移（小时），更换时按前驱表最后有效读数冻结；跨表修订重算时沿后继表更新';
COMMENT ON COLUMN meter.recalc_version IS '重算版本号，初始 1；本表 offset 或其读数引发跨表重算时加一';
COMMENT ON COLUMN meter.created_at IS '工时表产生时刻（UTC）';
COMMENT ON COLUMN meter.closed_at IS '工时表关闭时刻（UTC）；ACTIVE 时为 NULL';

-- 工时表跨表重算审计：旧表最后有效读数修订引发后继链重算时追加一行。
CREATE TABLE IF NOT EXISTS meter_chain_recompute (
    recompute_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id VARCHAR(64) NOT NULL,
    recompute_no INT NOT NULL,
    triggered_meter_key VARCHAR(64) NOT NULL,
    triggered_reading_id VARCHAR(64) NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    from_raw_hours DECIMAL(22,6) NOT NULL,
    to_raw_hours DECIMAL(22,6) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_recompute_no UNIQUE (equipment_id, recompute_no)
);
COMMENT ON TABLE meter_chain_recompute IS '工时表链条跨表重算记录：每次因旧表最后有效读数变更导致的整链重算追加一行';
COMMENT ON COLUMN meter_chain_recompute.recompute_id IS '重算记录自增主键';
COMMENT ON COLUMN meter_chain_recompute.equipment_id IS '所属设备标识';
COMMENT ON COLUMN meter_chain_recompute.recompute_no IS '设备内重算序号，从 1 开始递增';
COMMENT ON COLUMN meter_chain_recompute.triggered_meter_key IS '触发重算的（已关闭）工时表 meterKey';
COMMENT ON COLUMN meter_chain_recompute.triggered_reading_id IS '触发重算的最后有效读数 readingId';
COMMENT ON COLUMN meter_chain_recompute.request_id IS '触发重算的修订请求 requestId';
COMMENT ON COLUMN meter_chain_recompute.from_raw_hours IS '修订前最后有效读数原始工时（小时）';
COMMENT ON COLUMN meter_chain_recompute.to_raw_hours IS '修订后最后有效读数原始工时（小时）';
COMMENT ON COLUMN meter_chain_recompute.created_at IS '重算完成时刻（UTC）';

-- 工时读数当前值表：reading_id 设备内唯一，同设备同一采样时刻仅一条；从属于某张工时表。
-- raw_hours 为该表原始工时；virtual_hours 为跨表连续虚拟工时；cumulative_minutes 为虚拟分钟缓存（四舍五入）。
CREATE TABLE IF NOT EXISTS reading (
    equipment_id VARCHAR(64) NOT NULL,
    reading_id VARCHAR(64) NOT NULL,
    meter_key VARCHAR(64) NOT NULL,
    sampled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    raw_hours DECIMAL(22,6) NOT NULL,
    virtual_hours DECIMAL(22,6) NOT NULL,
    cumulative_minutes BIGINT NOT NULL,
    revision_no INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (equipment_id, reading_id),
    CONSTRAINT uq_reading_sampled_at UNIQUE (equipment_id, sampled_at)
);
COMMENT ON TABLE reading IS '工时读数当前值：同一工时表内按采样时刻排序后原始工时须单调不减，且不得小于该表 initial_raw_hours';
COMMENT ON COLUMN reading.equipment_id IS '所属设备标识';
COMMENT ON COLUMN reading.reading_id IS '读数标识，设备内唯一';
COMMENT ON COLUMN reading.meter_key IS '读数所属工时表 meterKey';
COMMENT ON COLUMN reading.sampled_at IS 'UTC 采样时刻；同设备同一时刻仅允许一条读数';
COMMENT ON COLUMN reading.raw_hours IS '表内原始工时读数（小时），非负';
COMMENT ON COLUMN reading.virtual_hours IS '跨表连续虚拟工时（小时）= offset_hours + raw_hours - initial_raw_hours';
COMMENT ON COLUMN reading.cumulative_minutes IS '虚拟工时换算分钟缓存（ROUND(virtual_hours*60)），保养周期按分钟比较';
COMMENT ON COLUMN reading.revision_no IS '当前修订号，初始 1，每次修订加一';
COMMENT ON COLUMN reading.created_at IS '读数登记时刻（UTC）';
COMMENT ON COLUMN reading.updated_at IS '最近一次修订时刻（UTC）';

-- 读数修订历史：每次修订追加一行，保留全部历史值。
CREATE TABLE IF NOT EXISTS reading_revision (
    equipment_id VARCHAR(64) NOT NULL,
    reading_id VARCHAR(64) NOT NULL,
    revision_no INT NOT NULL,
    raw_hours DECIMAL(22,6) NOT NULL,
    cumulative_minutes BIGINT NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (equipment_id, reading_id, revision_no)
);
COMMENT ON TABLE reading_revision IS '读数修订历史：revision_no=1 为初始登记值，其后每行对应一次修订';
COMMENT ON COLUMN reading_revision.equipment_id IS '所属设备标识';
COMMENT ON COLUMN reading_revision.reading_id IS '读数标识';
COMMENT ON COLUMN reading_revision.revision_no IS '修订号，从 1 开始递增';
COMMENT ON COLUMN reading_revision.raw_hours IS '该修订版本的表内原始工时（小时）';
COMMENT ON COLUMN reading_revision.cumulative_minutes IS '该修订生效时的虚拟工时分钟快照';
COMMENT ON COLUMN reading_revision.request_id IS '产生该修订的请求 requestId';
COMMENT ON COLUMN reading_revision.created_at IS '该修订生效时刻（UTC）';

-- 保养记录：锚定某读数的特定修订号，保存锚点时刻与工时快照，不允许删除。
CREATE TABLE IF NOT EXISTS maintenance (
    maintenance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id VARCHAR(64) NOT NULL,
    reading_id VARCHAR(64) NOT NULL,
    anchor_revision_no INT NOT NULL,
    anchor_sampled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    anchor_virtual_hours DECIMAL(22,6) NOT NULL,
    anchor_cumulative_minutes BIGINT NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_maintenance_equipment ON maintenance (equipment_id, anchor_sampled_at);
COMMENT ON TABLE maintenance IS '保养记录：锚点时间须严格晚于上次保养锚点；作为锚点的读数不可再修订；锚点虚拟工时随链条重算更新';
COMMENT ON COLUMN maintenance.maintenance_id IS '保养记录自增主键';
COMMENT ON COLUMN maintenance.equipment_id IS '所属设备标识';
COMMENT ON COLUMN maintenance.reading_id IS '锚点读数标识';
COMMENT ON COLUMN maintenance.anchor_revision_no IS '锚点读数在保养完成时的修订号';
COMMENT ON COLUMN maintenance.anchor_sampled_at IS '锚点读数的 UTC 采样时刻（快照）';
COMMENT ON COLUMN maintenance.anchor_virtual_hours IS '锚点读数在保养完成时的跨表虚拟工时快照（小时），随跨表重算刷新';
COMMENT ON COLUMN maintenance.anchor_cumulative_minutes IS '锚点虚拟工时换算分钟快照（随重算刷新），用于到期判定';
COMMENT ON COLUMN maintenance.request_id IS '完成保养请求的 requestId';
COMMENT ON COLUMN maintenance.completed_at IS '保养完成登记时刻（UTC）';

-- 幂等去重表：requestId 全局唯一；仅成功结果占键，失败回滚不占键。
CREATE TABLE IF NOT EXISTS idempotency_request (
    request_id VARCHAR(128) NOT NULL PRIMARY KEY,
    operation VARCHAR(48) NOT NULL,
    request_fingerprint VARCHAR(512) NOT NULL,
    response_body CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
COMMENT ON TABLE idempotency_request IS '写操作幂等去重：同键同参重放原成功结果（含更换链完整快照），同键异参返回 409';
COMMENT ON COLUMN idempotency_request.request_id IS '全局唯一请求标识（含更换请求 replacementKey）';
COMMENT ON COLUMN idempotency_request.operation IS '操作类型（登记设备/新增读数/修订/完成保养/更换工时表/工时表读数）';
COMMENT ON COLUMN idempotency_request.request_fingerprint IS '业务参数指纹（不含 requestId），用于同键异参判定';
COMMENT ON COLUMN idempotency_request.response_body IS '原成功响应报文（JSON），重放时原样返回';
COMMENT ON COLUMN idempotency_request.created_at IS '首次成功处理时刻（UTC）';
