-- 设备工时保养判定：H2（MODE=MySQL）自动建表脚本。
-- 所有时刻字段均为 UTC（TIMESTAMP WITH TIME ZONE），分钟数为非负整数。

-- 设备主表：每台设备一行，版本号用于写操作乐观并发控制。
CREATE TABLE IF NOT EXISTS equipment (
    equipment_id VARCHAR(64) NOT NULL PRIMARY KEY,
    maintenance_period_minutes BIGINT NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
COMMENT ON TABLE equipment IS '设备主表：每台设备一行';
COMMENT ON COLUMN equipment.equipment_id IS '设备唯一标识（客户端提供）';
COMMENT ON COLUMN equipment.maintenance_period_minutes IS '保养周期（分钟），正整数，登记后不可修改';
COMMENT ON COLUMN equipment.version IS '设备版本号，初始 1；新增读数/修订/完成保养均校验 expectedVersion 并加一';
COMMENT ON COLUMN equipment.created_at IS '登记时刻（UTC）';

-- 工时读数当前值表：reading_id 设备内唯一，同设备同一采样时刻仅一条。
CREATE TABLE IF NOT EXISTS reading (
    equipment_id VARCHAR(64) NOT NULL,
    reading_id VARCHAR(64) NOT NULL,
    sampled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cumulative_minutes BIGINT NOT NULL,
    revision_no INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (equipment_id, reading_id),
    CONSTRAINT uq_reading_sampled_at UNIQUE (equipment_id, sampled_at)
);
COMMENT ON TABLE reading IS '工时读数当前值：按采样时刻排序后累计分钟须单调不减';
COMMENT ON COLUMN reading.equipment_id IS '所属设备标识';
COMMENT ON COLUMN reading.reading_id IS '读数标识，设备内唯一';
COMMENT ON COLUMN reading.sampled_at IS 'UTC 采样时刻；同设备同一时刻仅允许一条读数';
COMMENT ON COLUMN reading.cumulative_minutes IS '当前累计工时（分钟），非负整数，随修订更新';
COMMENT ON COLUMN reading.revision_no IS '当前修订号，初始 1，每次修订加一';
COMMENT ON COLUMN reading.created_at IS '读数登记时刻（UTC）';
COMMENT ON COLUMN reading.updated_at IS '最近一次修订时刻（UTC）';

-- 读数修订历史：每次修订追加一行，保留全部历史值。
CREATE TABLE IF NOT EXISTS reading_revision (
    equipment_id VARCHAR(64) NOT NULL,
    reading_id VARCHAR(64) NOT NULL,
    revision_no INT NOT NULL,
    cumulative_minutes BIGINT NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (equipment_id, reading_id, revision_no)
);
COMMENT ON TABLE reading_revision IS '读数修订历史：revision_no=1 为初始登记值，其后每行对应一次修订';
COMMENT ON COLUMN reading_revision.equipment_id IS '所属设备标识';
COMMENT ON COLUMN reading_revision.reading_id IS '读数标识';
COMMENT ON COLUMN reading_revision.revision_no IS '修订号，从 1 开始递增';
COMMENT ON COLUMN reading_revision.cumulative_minutes IS '该修订版本的累计工时（分钟）';
COMMENT ON COLUMN reading_revision.request_id IS '产生该修订的请求 requestId';
COMMENT ON COLUMN reading_revision.created_at IS '该修订生效时刻（UTC）';

-- 保养记录：锚定某读数的特定修订号，保存锚点时刻与工时快照，不允许删除。
CREATE TABLE IF NOT EXISTS maintenance (
    maintenance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id VARCHAR(64) NOT NULL,
    reading_id VARCHAR(64) NOT NULL,
    anchor_revision_no INT NOT NULL,
    anchor_sampled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    anchor_cumulative_minutes BIGINT NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_maintenance_equipment ON maintenance (equipment_id, anchor_sampled_at);
COMMENT ON TABLE maintenance IS '保养记录：锚点时间须严格晚于上次保养锚点；作为锚点的读数不可再修订';
COMMENT ON COLUMN maintenance.maintenance_id IS '保养记录自增主键';
COMMENT ON COLUMN maintenance.equipment_id IS '所属设备标识';
COMMENT ON COLUMN maintenance.reading_id IS '锚点读数标识';
COMMENT ON COLUMN maintenance.anchor_revision_no IS '锚点读数在保养完成时的修订号';
COMMENT ON COLUMN maintenance.anchor_sampled_at IS '锚点读数的 UTC 采样时刻（快照）';
COMMENT ON COLUMN maintenance.anchor_cumulative_minutes IS '锚点读数在保养完成时的累计工时快照（分钟）';
COMMENT ON COLUMN maintenance.request_id IS '完成保养请求的 requestId';
COMMENT ON COLUMN maintenance.completed_at IS '保养完成登记时刻（UTC）';

-- 保养延期记录：申请/批准/拒绝/周期结束失效全量留痕；批准后阈值快照不可变。
CREATE TABLE IF NOT EXISTS deferral (
    deferral_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id VARCHAR(64) NOT NULL,
    defer_key VARCHAR(64) NOT NULL,
    cycle_no INT NOT NULL,
    defer_minutes BIGINT NOT NULL,
    reason VARCHAR(512) NOT NULL,
    applicant VARCHAR(64) NOT NULL,
    approver VARCHAR(64),
    reject_reason VARCHAR(512),
    status VARCHAR(16) NOT NULL,
    applied_cumulative_minutes BIGINT NOT NULL,
    original_threshold_minutes BIGINT,
    new_threshold_minutes BIGINT,
    request_id VARCHAR(128) NOT NULL,
    decision_request_id VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    decided_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_deferral_key UNIQUE (equipment_id, defer_key)
);
CREATE INDEX IF NOT EXISTS idx_deferral_equipment ON deferral (equipment_id, cycle_no, status);
COMMENT ON TABLE deferral IS '保养延期记录：同一设备同时仅允许一条 PENDING；批准后阈值快照不可变';
COMMENT ON COLUMN deferral.deferral_id IS '延期记录自增主键';
COMMENT ON COLUMN deferral.equipment_id IS '所属设备标识';
COMMENT ON COLUMN deferral.defer_key IS '延期业务标识，设备内唯一（含历史记录，不可复用）';
COMMENT ON COLUMN deferral.cycle_no IS '所属保养周期序号：申请时该设备已完成保养次数，从 0 计';
COMMENT ON COLUMN deferral.defer_minutes IS '申请延期分钟数，1～10080；单次不得超过保养周期 25%';
COMMENT ON COLUMN deferral.reason IS '申请原因';
COMMENT ON COLUMN deferral.applicant IS '申请人（维护角色标识）';
COMMENT ON COLUMN deferral.approver IS '审批人（维护角色标识）；批准时必须与申请人不同，未审批为 NULL';
COMMENT ON COLUMN deferral.reject_reason IS '拒绝理由，仅拒绝时填写，否则为 NULL';
COMMENT ON COLUMN deferral.status IS '状态：PENDING 待审批 / APPROVED 已批准 / REJECTED 已拒绝 / EXPIRED 周期结束失效';
COMMENT ON COLUMN deferral.applied_cumulative_minutes IS '申请时设备最新累计工时快照（分钟）';
COMMENT ON COLUMN deferral.original_threshold_minutes IS '批准时本周期原阈值（分钟）= 保养周期 + 此前已累计批准延期；未批准为 NULL';
COMMENT ON COLUMN deferral.new_threshold_minutes IS '批准时本周期新阈值（分钟）= 原阈值 + 本次延期；未批准为 NULL';
COMMENT ON COLUMN deferral.request_id IS '延期申请请求的 requestId';
COMMENT ON COLUMN deferral.decision_request_id IS '批准/拒绝请求的 requestId，未审批为 NULL';
COMMENT ON COLUMN deferral.created_at IS '申请时刻（UTC）';
COMMENT ON COLUMN deferral.decided_at IS '审批或周期结束失效时刻（UTC），未审批为 NULL';

-- 幂等去重表：requestId 全局唯一；仅成功结果占键，失败回滚不占键。
CREATE TABLE IF NOT EXISTS idempotency_request (
    request_id VARCHAR(128) NOT NULL PRIMARY KEY,
    operation VARCHAR(48) NOT NULL,
    request_fingerprint VARCHAR(512) NOT NULL,
    response_body CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
COMMENT ON TABLE idempotency_request IS '写操作幂等去重：同键同参重放原成功结果，同键异参返回 409';
COMMENT ON COLUMN idempotency_request.request_id IS '全局唯一请求标识';
COMMENT ON COLUMN idempotency_request.operation IS '操作类型（登记设备/新增读数/修订/完成保养/延期申请/延期批准/延期拒绝）';
COMMENT ON COLUMN idempotency_request.request_fingerprint IS '业务参数指纹（不含 requestId），用于同键异参判定';
COMMENT ON COLUMN idempotency_request.response_body IS '原成功响应报文（JSON），重放时原样返回';
COMMENT ON COLUMN idempotency_request.created_at IS '首次成功处理时刻（UTC）';
