package com.example.starter.maintenance;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

/**
 * 历史库兼容迁移测试（独立 H2 内存库，不经过 Spring 启动）：
 * 先用旧版结构（maintenance 无 item_code、无 maintenance_item 表）造历史数据，
 * 再执行正式 schema.sql，断言旧保养记录迁移为 DEFAULT、DEFAULT 项目按设备原周期补建，
 * 且脚本可重复执行（幂等）。
 */
class MaintenanceSchemaMigrationTests {

    @Test
    void legacyDatabase_migratesDefaultItemsAndIsIdempotent() throws Exception {
        String url = "jdbc:h2:mem:maintenance_migration_test;MODE=MySQL;DATABASE_TO_LOWER=TRUE"
                + ";DB_CLOSE_DELAY=-1";
        try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
            createLegacySchema(connection);
            seedLegacyData(connection);

            // 第一次执行：建缺失表 + 补 item_code 列 + 迁移历史数据
            runSchema(connection);
            assertMigrationResult(connection);

            // 第二次执行：全部语句幂等，数据不变
            runSchema(connection);
            assertMigrationResult(connection);

            try (Statement shutdown = connection.createStatement()) {
                shutdown.execute("SHUTDOWN");
            }
        }
    }

    private void createLegacySchema(Connection connection) throws Exception {
        try (Statement st = connection.createStatement()) {
            st.execute("""
                    CREATE TABLE equipment (
                        equipment_id VARCHAR(64) NOT NULL PRIMARY KEY,
                        maintenance_period_minutes BIGINT NOT NULL,
                        version BIGINT NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL
                    )""");
            // 旧版保养表：没有 item_code 列。
            st.execute("""
                    CREATE TABLE maintenance (
                        maintenance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        equipment_id VARCHAR(64) NOT NULL,
                        reading_id VARCHAR(64) NOT NULL,
                        anchor_revision_no INT NOT NULL,
                        anchor_sampled_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        anchor_cumulative_minutes BIGINT NOT NULL,
                        request_id VARCHAR(128) NOT NULL,
                        completed_at TIMESTAMP WITH TIME ZONE NOT NULL
                    )""");
        }
    }

    private void seedLegacyData(Connection connection) throws Exception {
        OffsetDateTime ts = Instant.parse("2026-08-01T00:00:00Z").atOffset(ZoneOffset.UTC);
        try (Statement st = connection.createStatement()) {
            st.execute("INSERT INTO equipment (equipment_id, maintenance_period_minutes, version,"
                    + " created_at) VALUES ('eq-old', 333, 9, '" + ts + "')");
            st.execute("INSERT INTO maintenance (equipment_id, reading_id, anchor_revision_no,"
                    + " anchor_sampled_at, anchor_cumulative_minutes, request_id, completed_at)"
                    + " VALUES ('eq-old', 'r1', 1, '" + ts + "', 100, 'old-mnt-1', '" + ts + "')");
            st.execute("INSERT INTO maintenance (equipment_id, reading_id, anchor_revision_no,"
                    + " anchor_sampled_at, anchor_cumulative_minutes, request_id, completed_at)"
                    + " VALUES ('eq-old', 'r2', 2, '" + ts + "', 250, 'old-mnt-2', '" + ts + "')");
        }
    }

    private void runSchema(Connection connection) {
        ResourceDatabasePopulator populator = new ResourceDatabasePopulator();
        populator.setContinueOnError(false);
        populator.setSqlScriptEncoding("UTF-8");
        populator.addScript(new ClassPathResource("schema.sql"));
        populator.populate(connection);
    }

    private void assertMigrationResult(Connection connection) throws Exception {
        try (Statement st = connection.createStatement()) {
            // 历史保养记录全部迁移为 DEFAULT 项目
            try (ResultSet rs = st.executeQuery("SELECT item_code FROM maintenance ORDER BY reading_id")) {
                int rows = 0;
                while (rs.next()) {
                    assertEquals("DEFAULT", rs.getString(1));
                    rows++;
                }
                assertEquals(2, rows);
            }
            // DEFAULT 项目按设备登记时原周期补建
            try (ResultSet rs = st.executeQuery(
                    "SELECT item_code, maintenance_period_minutes FROM maintenance_item"
                            + " WHERE equipment_id = 'eq-old'")) {
                int rows = 0;
                while (rs.next()) {
                    assertEquals("DEFAULT", rs.getString(1));
                    assertEquals(333L, rs.getLong(2));
                    rows++;
                }
                assertEquals(1, rows, "历史设备应恰好补建一个 DEFAULT 项目");
            }
            // 新表也已就位（历史设备无读数）
            try (ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM reading")) {
                rs.next();
                assertEquals(0, rs.getInt(1));
            }
            // 设备原有版本号不被迁移改写
            try (ResultSet rs = st.executeQuery(
                    "SELECT version FROM equipment WHERE equipment_id = 'eq-old'")) {
                rs.next();
                assertEquals(9, rs.getInt(1));
            }
        }
    }
}
