-- 本文件已不再使用：测试与本地运行统一使用 src/main/resources/schema-h2.sql（H2 MySQL 兼容模式），
-- 由 src/test/resources/application.yaml 的 spring.sql.init.schema-locations 指定；
-- MySQL 部署版建表脚本见 src/main/resources/schema.sql（含中文 COMMENT）。
